# Generated by Django 4.0.6 on 2023-06-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('wallet_address', models.CharField(max_length=100)),
            ],
        ),
    ]
