# Generated by Django 4.0.6 on 2023-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='item_images')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('posting_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Country', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Full name', max_length=100),
        ),
    ]
