# Generated by Django 4.0.6 on 2023-07-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
